spring.application.name=AutomaticApply

# Use environment variables (SAFE for deployment)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server port (important for Render/Cloud)
server.port=${PORT:8080}