spring.application.name=AutomaticApply

#spring.datasource.url=jdbc:mysql://Localhost:3306/job_platform
#spring.datasource.username=root
#spring.datasource.password=Anuse@243


# Use environment variables (SAFE for deployment)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server port (important for Render/Cloud)
server.port=${PORT:8080}

# jsp pages path 
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp